import Head from 'next/head'
import { AiOutlineMail, AiFillLinkedin } from 'react-icons/ai';
import {useState, useEffect}from 'react'

export default function Home() {

  let [date, setDate] = useState(new Date());

  useEffect(() =>{
    let timer = setInterval(() => setDate(new Date()), 1000)
    return function cleanup() {
      clearInterval(timer);
    }
  }, []);

  const scrollUp = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    })

  }
  
  return (
    <>
    <div>
      <Head>
        <title>Ronald Beck CV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white overflow-hidden font-merriweather">
        
        <section className="w-11/12 mx-auto mb-20 mt-32 md:mt-20 lg:mt-44 lg:mb-28">
              <h2 className="text-8xl md:text-10xl mb-1 py-5 mt-20 lg:mb-2 sm:text-8xl font-bold">Ronald Beck</h2>
            <div className="flex justify-between">
              <h3 className="text-gray-700 text-xl">Aspiring Software Developer</h3>
              <h3 className="text-gray-700 text-xl">Based in London</h3>
            </div>
          <h3 className="text-gray-700 text-xl float-right">GMT {date.toLocaleTimeString('en-GB')}</h3>
          <hr className="w-full mx-auto border-black border-2 mt-2 lg:mt-8 sm:mt-8"></hr>
          <div className="flex h-1">
          <a className="ml-auto hover:mt-1 " href="mailto:ronaldbeck@hotmail.co.uk"><AiOutlineMail size={50}/></a>
          <a className="hover:mt-1 " href="https://www.linkedin.com/in/ronald-beck-03104a213/" target="_blank"><AiFillLinkedin size={50}/></a>
          </div>
        </section>

        <section className="w-11/12 mx-auto mt-5">
          <h3 className="text-4xl text-center mt-10 mb-5">Get to know me</h3>
          <div className="sm:flex">            
            <p className="border-2 rounded-2xl p-5 sm:w-1/2 border-black sm:ml-auto">Good day, everyone! My name is Ronald, I am a hard-working 20-year-old from South East London with a strong work ethic and a desire to learn and develop my skills and knowledge in software development. As technology and programming is a passion of mine, I find it extremely enjoyable and exciting which fuels my self motivation to always improve and learn.<br></br><br></br> I am currently looking for a software development opportunity (apprenticeship or trainee role) to bring my contagious positive energy, desire to learn and improve from everyone, and produce quality work.</p>
            <img src="https://i.ibb.co/61hpy4S/Picture-Of-Me.png" className="mx-auto sm:mx-0 mt-5 sm:0 w-80 h-72 md:h-auto sm:ml-4 border-2 rounded-full border-black sm:mr-auto drop-shadow-2xl"/> 
          </div>
          <hr className="w-full mx-auto border-stone-400 border-1 mt-11 mb-10"></hr>
        </section>

        <section className="w-11/12 mx-auto mt-5">
        <h3 className="text-4xl text-center mb-5">My work experience</h3>
          <div className="sm:flex">
            <div className="border-2 rounded-2xl p-2 sm:w-2/4 border-black sm:mr-5 mb-5 sm:mb-0">
              <p className="text-xl">Software Developer Trainee <span className="text-sm">- VMA Digital</span></p>
              <p>10/2022 - 11/2022</p>
              <hr className="my-2"></hr>
              <p className="text-lg">Responsibilities:</p>
              <li>Problem solving website issues or errors in React.js, Next,js, Typescript</li>
              <li>Making chanes to website using Tailwind CSS or DaisyUI</li>
              <li>Using git to add branches and commits to the project repository</li>
              <li>Responding to tickets assigned to me via Github or Jira Software</li>
              <li>Making pull requests on Github of my coding solutions to tickets</li>
              <p className="text-lg">Achievements:</p>
              <li>Learned about the different technologies, languages, and frameworks that build up a website</li>
              <li>Gained an insight into the daily tasks and activities of a software developer</li>
              <li>Developed problem-solving skills</li>
              <li>Developed collaborative teamwork skills</li>
              <li>Successfully can use git within a project</li>
              <li>Developed verbal and written communication using Slack and Github</li>
              <li>Gained experience with: React.js, Next.js, Node.js, TypeScript, Tailwind CSS, DaisyUI, git, Github, GitPod, Gatsby.js, Configuring Visual Studio Code, Configuring Android Studio, using FireBase</li>
            </div>
            <div className="border-2 rounded-2xl p-2 w-fit sm:w-2/4 border-black sm:ml-auto">
            <p className="text-xl">Cyber security traineeship <span className="text-sm">- Vasave Business Solutions </span></p>
            <p>08/2022 - 09/2022</p>
            <hr className="my-2"></hr>
            <p className="text-lg">Responsibilities:</p>
            <li>Creating and editing policies</li>
            <li>Editing audits</li>
            <li>Reviewing company procedures</li>
            <li>Reviewing company forms</li>
            <p className="text-lg">Achievements</p>
            <li>Build upon cyber security knowledge of audits, policies, procedures, and forms</li>
            <li>Improved confidence, especially in tough situations</li>
            <li>Improved oral and written communicative skills</li>
            <li>Gained office experience</li>
            <li>Worked in many different working dynamics with other colleagues/trainees</li>
            </div>
          </div>
          <hr className="w-full mx-auto border-stone-400 border-1 mt-11 mb-10 snap-center"></hr>
        </section>

        <section className="w-11/12 mx-auto mt-5">
        <h3 className="text-4xl text-center mb-5">My education</h3>
          <div className="flex flex-row">
            <div className="border-2 rounded-2xl p-2 w-1/2 border-black mr-4">
              <p className="text-xl">Software Development Traineeship <span className="text-sm">- London Vesta College</span></p>
              <p>08/2022 - 09/2022</p>
              <hr className="my-2"></hr>
              <li>Exciting daily lessons based on different syntax, concepts, and different programming tasks and projects</li>
              <li>Studied the fundamentals of one object-orientated language, Java. As well as HTML, CSS, vanillia JavaScript, and software testing theory.</li>
            </div>
            <div className="border-2 rounded-2xl p-2 w-1/2 border-black mr-4">
              <p className="text-xl">Cyber security traineeship <span className="text-sm">- London Learning Consortium</span></p>
              <p>09/2021 - 01/2022</p>
              <hr className="my-2"></hr>
              <li>Studied about customer serivice and employability skills</li>
              <li>Achieved City & Guilds Level 1 Introduction to Customer Service</li>
              <li>Highfield Level 1 Certificate in Personal Development and Employment</li>
            </div>
          </div>
          <div className="flex flex-row mt-5">
            <div className="border-2 rounded-2xl p-2 w-1/2 border-black mr-4">
              <p className="text-xl"> Sixth Form <span className="text-sm">- Harris Academy Beckenham</span></p>
              <p>09/2019 - 08/2021</p>
              <hr className="my-2"></hr>
              <li>Achieved grade DD in OCR Cambridge Technical Diploma in ICT</li>
              <li>The ICT course was very broad, having many different ICT topics, such as: product development, cloud technology, computer networks, and much more.</li>
              <li>Achieved grade C in A-Level History</li>
            </div>
            <div className="border-2 rounded-2xl p-2 w-1/2 border-black mr-4">
              <p className="text-xl">Secondary School <span className="text-sm">- Harris Academy Beckenham</span></p>
              <p>09/2015 - 09/2019</p>
              <hr className="my-2"></hr>
              <li>9 GCSE’s including English, Maths and Double Science</li>
              <li>Also including Grade 6 Computer science and Grade 5 Maths</li>
            </div>
          </div>
          <hr className="w-full mx-auto border-stone-400 border-1 mt-11 mb-10"></hr>
        </section>

        <section className="w-11/12 mx-auto mt-5">
        <h3 className="text-4xl text-center mb-5">My top skills</h3>
          <div className="sm:flex mx-auto mt-10">
            <div className="border-2 rounded-2xl p-2 sm:w-1/4 border-black mx-auto mb-5 sm:mb-0">
            <p className="text-xl">Quick Learner</p>
            <hr className="my-2"></hr>
            <p>By being a quick learner it enables me to understand new information at a rapid pace therefore giving me the capability to learn and develop skills and build upon knowledge quickly. Within software development, this allows me to absorb concepts or instructions faster and identifying the most suitable solutions to problems in a short span of time. </p>
            </div>
            <div className="border-2 rounded-2xl p-2 sm:w-1/4 border-black mx-auto mb-5 sm:mb-0">
            <p className="text-xl">Communication</p>
            <hr className="my-2"></hr>
            <p>Whether it is oral or written communication on any platform or environment, I maintain a level of effective communication that builds trust amongst the organization and helps a drive for better results for individuals, teams, and organizations. This skill is essential in software development as it allows me to receive the correct information as well as produce it in order to maintain productivity and to stay within time frames. </p>
            </div>
            <div className="border-2 rounded-2xl p-2 sm:w-1/4 border-black mx-auto mb-5 sm:mb-0">
            <p className="text-xl">Dedication</p>
            <hr className="my-2"></hr>
            <p>My unwavering dedication that is a product of my passion for software development and technology will give me the commitment towards my work ethic to always want to be an outstanding employee and achieve my short/long term goals through my desire to learn and improve myself.</p>
            </div>
          </div>
          <hr className="w-full mx-auto border-white border-1 mt-11"></hr>
        </section>

        <h3 className="text-3xl text-center mb-5">Thanks for coming this far!</h3>
        <div className=" bg-black h-auto w-full pb-5">
          <section className="w-11/12 mx-auto h-auto">
            <h3 className="text-center text-4xl text-white pt-5"> Contact me!</h3>
            <h4 className="text-left text-2xl text-white pt-5"> Feel free to contact me!</h4>
            <div className="flex flex-row">
              <div className="border-2 border-white w-fit mt-5">
                <a className=" text-white" href="mailto:ronaldbeck@hotmail.co.uk"><AiOutlineMail size={50}/></a>
              </div>
              <div className="border-2 border-white w-fit mt-5">
                <p className="text-2xl sm:text-4xl text-white m-1 mx-auto sm:mx-0">Ronaldbeck@hotmail.co.uk</p>
              </div>
            </div>
            <div className="flex flex-row mt-5">
              <div className="border-2 border-white w-fit mt-5">
                <a className="text-white" href="https://www.linkedin.com/in/ronald-beck-03104a213/" target="_blank"><AiFillLinkedin size={50}/></a>
              </div>
              <div className="border-2 border-white w-fit mt-5">
                <p className="text-4xl text-white m-1">LinkedIn</p>
              </div>
            </div>
            <hr className="w-full mx-auto border-white border-1 mt-11"></hr>
            <h1 className="text-7xl sm:text-8xl text-white mt-5 text-center"> Have a wonderful day!</h1>
            <div className="mt-5 border-2 w-fit h-fit mx-auto">
              <p className="text-white text-2xl" onClick={scrollUp}>Click here to go back to top</p>
            </div>
          </section>

        </div>
      </main>
      </div>
    </>
  );
}
